language: node_js                                                             
node_js:
  - '4'
  - '5'
  - '6'
script:
  - npm run lint
  - npm run test -- --coverage
  - ./travis.sh
cache:
  directories:
    - node_modules
env:
  global:
    - secure: "GryjuBOwJbD44J/1bNl03FaUEfQATdJWU47ASTh2Sd8ICHE+2RIfTxg1i2dxmT9n+qiJJ7cCtzQwT/pKtA//kP7tj/Ko4XNRdI4G+v7ISRM96nevmYXe7d0ujdmcJ3L+cKGkzw+2b2zqUH3P1lUOSQtxsJhP8ZCyJsMytyc8kVY="
